flask_blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, validators


class PostForm(FlaskForm):
	title = StringField('Title', validators=[validators.DataRequired()])
	content = TextAreaField('Content', validators=[validators.DataRequired()])
	submit = SubmitField('Post')

flask_blog/main/routes.py
from flask import Blueprint, render_template, request, url_for
from flask_blog.models import Post


main = Blueprint('main', __name__)


@main.route("/")
def home():
	page = request.args.get('page', 1, type=int)
	limit = min(request.args.get('limit', 5, type=int), 100)
	posts = Post.query.order_by(Post.date_created.desc()).paginate(page=page, per_page=limit)
	return render_template('home.html', posts=posts)


@main.route('/about')
def about():
	return render_template("about.html", title='About')




# ----- UNIQUE ----- #
@main.route('/favicon.ico')
def favicon():
	return url_for('static', filename='favicon.ico')

flask_blog/posts/routes.py
from flask import Blueprint, render_template, request, url_for, flash, redirect, abort, jsonify
from flask_login import current_user, login_required
from flask_blog import db
from flask_blog.models import Post, Replies
from flask_blog.posts.forms import PostForm

posts = Blueprint('posts', __name__)

@posts.route('/post/<int:post_id>')
def post(post_id: int):
	post = Post.query.get_or_404(post_id)
	replies = Replies.query.filter_by(post_id=post.id).order_by(Replies.date_created.asc())
	return render_template('post.html', title=post.title, post=post, replies=replies)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def newPost():
	form = PostForm()
	if form.validate_on_submit():
		post = Post(title=form.title.data, content=form.content.data, author=current_user)
		db.session.add(post)
		db.session.commit()
		flash('Post posted.', 'success')
		return redirect(url_for('main.home'))
	return render_template('create_post.html', title='New Post', legend='New Post', form=form)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def updatePost(post_id: int):
	post = Post.query.get_or_404(post_id)
	if post.author != current_user and current_user.privilege_level >= 1:
		abort(403)
	form = PostForm()
	# from wtforms.widgets.core.py line 259
	form.submit.label.text = 'Update'
	if form.validate_on_submit():
		post.title = form.title.data
		post.content = form.content.data
		post.is_modified = True
		db.session.commit()
		flash('Post successfully updated.', 'success')
		return redirect(url_for('posts.post', post_id=post.id))
	elif request.method == 'GET':
		form.title.data = post.title
		form.content.data = post.content
	return render_template('create_post.html', title='Update Post', legend='Update Post', form=form)


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def deletePost(post_id: int):
	post = Post.query.get_or_404(post_id)
	if post.author != current_user and current_user.privilege_level >= 1:
		abort(403)
	db.session.delete(post)
	db.session.commit()
	flash('Your post has been deleted.', 'success')
	return redirect(url_for('main.home'))


@posts.route('/reply', methods=['POST'])
@login_required
def replyPost():
	post_id = request.form.get('post_id', type=int)
	replyContent = request.form.get('reply_content')
	print(post_id, replyContent)
	if post_id and replyContent:
		reply = Replies(post_id=post_id, content=replyContent, user_id=current_user.id)
		db.session.add(reply)
		db.session.commit()
		return jsonify({'success':True})
	return jsonify({'success':False})


@posts.route('/reply/delete', methods=['POST'])
@login_required
def deleteReply():
	reply_id = request.form.get('reply_id', type=int)
	if reply_id:
		reply = Replies.query.get_or_404(reply_id)
		if reply.author != current_user and current_user.privilege_level >= 1:
			abort(403)
		db.session.delete(reply)
		db.session.commit()
		return jsonify({'success':True})
	return jsonify({'success':False})

flask_blog/users/routes.py
from flask import Blueprint, render_template, url_for, request, flash, redirect
from flask_login import login_user, logout_user, current_user, login_required
from flask_blog import db, bcrypt
from flask_blog.models import User, Post
from flask_blog.users.forms import *
from flask_blog.users.utils import save_picture, send_reset_email


users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RegistrationForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user = User(username=form.username.data, email=form.email.data, password=hashed_password)
		db.session.add(user)
		db.session.commit()
		flash(f'Account created successfully.', 'success')
		return redirect(url_for('users.login'))
	return render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = LoginForm()
	if form.validate_on_submit() or request.method == 'POST':
		user = User.query.filter_by(email=form.email.data).first()
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			login_user(user, remember=form.rememberMe.data)
			flash('Login Successful!', 'success')
			nextPage = request.args.get('next')
			return redirect(nextPage) if nextPage else redirect(url_for('main.home'))
		flash('Login failed. Please check your email and password again.', 'danger')
	return render_template('login.html', title='Login', form=form)


@users.route('/logout')
def logout():
	logout_user()
	return redirect(url_for('main.home'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
	form = UpdateAccountForm()
	if form.validate_on_submit():
		if form.profile_picture.data:
			current_user.image_file = save_picture(form.profile_picture.data)
		current_user.username = form.username.data
		current_user.email = form.email.data
		db.session.commit()
		flash('Your account has been updated', 'success')
		return redirect(url_for('users.account'))
	elif request.method == 'GET':
		form.username.data = current_user.username
		form.email.data = current_user.email
	return render_template('account.html', title='Account', form=form)


@users.route("/user/<string:username>")
@users.route("/u/<int:user_id>")
@users.route("/u/<string:username>")
def userPosts(username=None, user_id=None):
	page = request.args.get('page', 1, type=int)
	limit = min(request.args.get('limit', 5, type=int), 100)
	if username:
		user = User.query.filter_by(username=username).first_or_404()
	elif user_id:
		user = User.query.get_or_404(user_id)
	else:
		return redirect(url_for('main.home'))
	posts = Post.query.filter_by(author=user)\
			.order_by(Post.date_created.desc())\
			.paginate(page=page, per_page=limit)
	#posts.reverse()
	return render_template('user_posts.html', posts=posts, user=user)


@users.route('/reset_password', methods=['GET', 'POST'])
def requestResetPassword():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RequestResetPasswordForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		send_reset_email(user)
		flash('An email has been sent with instructions to reset your password.', 'info')
		return redirect(url_for('users.login'))
	return render_template('reset_password_request.html', title='Reset Password', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	user = User.verify_reset_token(token)
	if user is None:
		flash('That is an invalid or expired token', 'warning')
		return redirect(url_for('users.requestResetPassword'))
	form = ResetPasswordForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user.password = hashed_password
		db.session.commit()
		flash(f'Your password has been updated! You can now log in with your new credentials.', 'success')
		return redirect(url_for('users.login'))
	return render_template('reset_token.html', title='Reset Password', form=form)

flask_blog/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <h3>About Page</h3>
        <p style="border-top: 0.05rem solid #a0a4ad;font-size:1.3rem">Hello There! It's Ren here. I wanna explain what this whole thing is. This is a copy of <a href="https://www.youtube.com/playlist?list=PL-osiE80TeTs4UjLw5MM6OjgkjFeUxCYH">CoreySchafer's Tutorial on Full Featured Web App.</a> While i have made some slight modifications to the project, like color scheme, code naming style, etc. Overall its structure is still the same as the original. Ummm, that's all i want to say, have a great day!</p>
    </div>
{% endblock %}
{% block sidebar %}
        <div class="col-md-4">
          <div class="content-section">
            <h3>Project Status</h3>
            <p class='text-muted'>Finished</p>
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Time Spent: 4 Days</li>
                <li class="list-group-item list-group-item-light">Database 100%</li>
                <li class="list-group-item list-group-item-light">Account 100%</li>
                <li class="list-group-item list-group-item-light">Posts 100%</li>
                <li class="list-group-item list-group-item-light">Error Handler 100%</li>
              </ul>
          </div>
        </div>
{% endblock sidebar %}

flask_blog/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
          <div class="media">
                <img class="rounded-circle account-img" src="{{ get_profile_picture(current_user) }}">
                <div class="media-body">
                      <h2 class="account-heading">{{ current_user.username }}</h2>
                      <p class="text-secondary">{{ current_user.email }}</p>
                </div>
          </div>
        <form action="" method="POST" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                {% if current_user.privilege_level <= 3 %}
                    <h5>User privilege level: {{ current_user.privilege_level }} <small class="text-muted" style="font-size:0.7rem">(Lower is higher)</small></h5>
                {% endif %}
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    <!-- Validation Error if error -->
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg form-control-md form-control-xs is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg form-control-md form-control-xs") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    <!-- Validation Error if error -->
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg form-control-md form-control-xs is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg form-control-md form-control-xs") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.profile_picture.label() }}
                    {{ form.profile_picture(class="form-control-file") }}
                    <small class="text-muted">Max file size is 25MB</small>
                    {% if form.profile_picture.errors %}
                        {% for error in form.profile_picture.errors %}
                            <span class="text-danger">{{ error }}</span><br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flask_blog/templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
          <a class="mr-2 link-primary" href="{{ url_for('users.userPosts', username=post.author.username) }}">
            <img src="{{ get_profile_picture(post.author) }}" width="40" height="40" class="rounded-circle mr-1">
          </a>
          <div class="media-body">
            <div class="article-metadata">
               <a class="mr-2 link-primary" href="{{ url_for('users.userPosts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">
                  <span id="{{post.id}}-time-created">{% if post.is_modified %} <small class="text-muted" style="font-size:0.75rem">(edited)</small> {% endif %}</span>
              </small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
        <script type="text/javascript">
            var timeElement = document.getElementById("{{post.id}}-time-created");
            var utcTime = "{{post.date_created.strftime('%Y-%m-%d %H:%M:%S')}}";
            var localDate = moment.utc(utcTime).local().fromNow();
            timeElement.innerHTML = localDate + timeElement.innerHTML;
        </script>
    {% endfor %}

    <ul class="pagination justify-content-center">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
            <a class="btn btn-info mb-4  ml-1" href="{{ url_for('main.home', page=page_num, limit=posts.per_page) }}">{{ page_num }}</a>
            {% else %}
            <a class="btn btn-outline-info mb-4  ml-1" href="{{ url_for('main.home', page=page_num, limit=posts.per_page) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            <p class="page-item">...</p>
        {% endif %}
    {% endfor %}
    </ul>

{% endblock content %}
{% block sidebar %}
        <div class="col-md-4">
          <div class="content-section">
            <h3>Project Status</h3>
            <p class='text-muted'>Finished
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Time Spent: 4 Days</li>
                <li class="list-group-item list-group-item-light">Database 100%</li>
                <li class="list-group-item list-group-item-light">Account 100%</li>
                <li class="list-group-item list-group-item-light">Posts 100%</li>
                <li class="list-group-item list-group-item-light">Error Handler 100%</li>
              </ul>
            </p>
          </div>
        </div>
{% endblock sidebar %}

flask_blog/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- DARK THEME FROM BOOTSWATCH-->
    <link rel="stylesheet" type="text/css" href="https://bootswatch.com/5/darkly/bootstrap.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    
    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" referrerpolicy="no-referrer" />

    {% if title %}
        <title>Flask Blog - {{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-expand-lg navbar-expand-xs navbar-dark bg-dark fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Flask Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            {% if current_user.is_authenticated %}
              <div class="navbar-nav mr-2">
                  <a class="nav-item nav-link" href="{{ url_for('posts.newPost') }}">New Post</a>
              </div>
              <div class="nav-item dropdown">
                  <button class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img src="{{ get_profile_picture(current_user) }}" width="40" height="40" class="rounded-circle mr-1"> {{ current_user.username }}
                  </button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item" href="{{ url_for('users.account') }}">Edit Profile</a>
                    <a class="dropdown-item" href="{{ url_for('users.logout') }}">Log Out</a>
                  </div>
              </div>
            {% else %}
              <div class="navbar-nav">
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              </div>
            {% endif %}
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{message}}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}

          {% block content %}{% endblock %}
        </div>
        {% block sidebar %}{% endblock %}
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- Popper.js then Bootstrap JS -->
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

flask_blog/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form action="" method="POST">
            {{ form.hidden_tag() }}
            <fieldset class="form-group bg-soft-white">
                <legend class="border-bottom mb-4">Log In</legend>

                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    <!-- Validation Error if error -->
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg form-control-md form-control-xs is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg form-control-md form-control-xs") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}

                    <!-- Validation Error if error -->
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg form-control-md form-control-xs is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors%}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg form-control-md form-control-xs") }}
                    {% endif %}
                </div>

                <div class="form-check">
                    {{ form.rememberMe(class="form-check-input bg-light") }}
                    {{ form.rememberMe.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.requestResetPassword') }}">Forgot Password?</a>
                </small>
            </div>

        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Don't Have An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Register Now</a>
        </small>
    </div>
{% endblock %}

flask_blog/templates/post.html
{% extends "layout.html" %}
{% block content %}
    <article class="media content-section">
        <img src="{{ get_profile_picture(post.author) }}" width="50" height="50" class="rounded-circle mr-1 mb-1">
        <div class="media-body">
            <div class="article-metadata">
                    <a class="mr-2 link-primary" href="#">{{ post.author.username }}</a>
                    <small class="text-muted">
                         <span id="post-time-created"></span>
                    </small>
                    {% if post.author == current_user or (current_user.is_authenticated and current_user.privilege_level <= 1) %}
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.updatePost', post_id=post.id)}}">Update</a>
                        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>

                    </div>
                    {% endif %}
            </div>
            <h2 class="article-title">{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
        <script type="text/javascript">
            var timeElement = document.getElementById("post-time-created");
            var utcTime = "{{post.date_created.strftime('%Y-%m-%d %H:%M:%S')}}";
            var localDate = moment.utc(utcTime).local().format('D MMMM YYYY HH:mm');
            timeElement.innerHTML = localDate;
        </script>
    </article>
    {% for reply in replies %}
        <div class="media content-section" style="width:85%;margin-left:15%">
            <img src="{{ get_profile_picture(reply.author) }}" width="30" height="30" class="rounded-circle mr-1 mb-1">
            <div class="media-body">
                <div class="article-metadata">
                        <a class="mr-2 link-primary" href="#">{{ reply.author.username }}</a>
                        <small class="text-muted">
                             <span id="reply-{{reply.id}}-time-created"></span>
                        </small>
                        {% if reply.author == current_user or (current_user.is_authenticated and current_user.privilege_level <= 1) %}
                        <div>
                            <!--
                            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.updatePost', post_id=post.id)}}">Update</a>
                            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                            -->
                        </div>
                        {% endif %}
                </div>
                <p class="article-content">{{ reply.content }}</p>
            </div>
            <script type="text/javascript">
                var timeElement = document.getElementById("reply-{{reply.id}}-time-created");
                var utcTime = "{{reply.date_created.strftime('%Y-%m-%d %H:%M:%S')}}";
                var localDate = moment.utc(utcTime).local().format('D MMMM YYYY HH:mm');
                timeElement.innerHTML = localDate;
            </script>
        </div>
    {% endfor %}
    <script type="text/javascript">
        function replyViaAjax() {
            let data = {post_id : {{post.id}},reply_content : $('#replyContent').val()};
            $.ajax({data : data, type : 'POST', url : '/reply'})
            .done(function(data) {
                let to_be_continued = true;
            });

            //event.preventDefault();
        }
    </script>
        <div class="media content-section" style="width:85%;margin-left:15%">
            <img src="{{ get_profile_picture(current_user) }}" width="30" height="30" class="rounded-circle mr-1 mb-1">
            <div class="media-body">
                <div class="article-metadata">
                        <a class="mr-2 link-primary" href="#">{{ current_user.username }}</a>
                        <small class="text-muted">
                             <span id="userReply"></span>
                        </small>
                </div>
                <form class="form-inline">
                <div class="form-group" style="width:100%;margin-top:0.3rem">
                    <input type="text" class="form-control mr-2" id="replyContent" style="width:80%" placeholder="Reply Something">
                    <button class="rounded-circle btn btn-secondary" onclick="replyViaAjax()"><i class="fa fa-paper-plane" aria-hidden="true"></i></button>
                </div>
                </form>
            </div>
        </div>


    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title text-white" id="deleteModalLabel">Delete Post?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <form action="{{ url_for('posts.deletePost', post_id=post.id) }}" method="POST">
                        <input type="submit" class="btn btn-danger" value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

flask_blog/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% if current_user.is_authenticated and current_user.privilege_level <= 3 %}
        <h5>{{ user.username }}'s privilege level: {{ user.privilege_level }} <small class="text-muted" style="font-size:0.7rem">(Lower is higher)</small></h5>
    {% endif %}
    {% for post in posts.items %}
        <article class="media content-section">
          <img src="{{ get_profile_picture(post.author) }}" width="40" height="40" class="rounded-circle mr-1">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2 link-primary" href="{{ url_for('users.userPosts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">
                  <span id="{{post.id}}-time-created">{% if post.is_modified %} <small class="text-muted" style="font-size:0.75rem">(edited)</small> {% endif %}</span>
              </small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
        <script type="text/javascript">
            var timeElement = document.getElementById("{{post.id}}-time-created");
            var utcTime = "{{post.date_created.strftime('%Y-%m-%d %H:%M:%S')}}";
            var localDate = moment.utc(utcTime).local().fromNow();
            timeElement.innerHTML = localDate + timeElement.innerHTML;
        </script>
    {% endfor %}

    <ul class="pagination justify-content-center">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
            <a class="btn btn-info mb-4  ml-1" href="{{ url_for('users.userPosts', username=user.username, page=page_num, limit=posts.per_page) }}">{{ page_num }}</a>
            {% else %}
            <a class="btn btn-outline-info mb-4  ml-1" href="{{ url_for('users.userPosts', username=user.username, page=page_num, limit=posts.per_page) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            <p class="page-item">...</p>
        {% endif %}
    {% endfor %}
    </ul>

{% endblock content %}